---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-fusion-storage-openshift-io-v1alpha1-fusionaccess
  failurePolicy: Fail
  name: fusion.storage.openshift.io
  rules:
  - apiGroups:
    - fusion.storage.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - fusionaccesses
  sideEffects: None
