---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-purple-purplestorage-com-v1alpha1-purplestorage
  failurePolicy: Fail
  name: mpurplestorage.kb.io
  rules:
  - apiGroups:
    - purple.purplestorage.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - purplestorages
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-purple-purplestorage-com-v1alpha1-purplestorage
  failurePolicy: Fail
  name: vpurplestorage.kb.io
  rules:
  - apiGroups:
    - purple.purplestorage.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - purplestorages
  sideEffects: None
