---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-scale-storage-openshift-io-v1alpha1-storagescale
  failurePolicy: Fail
  name: scale.storage.openshift.io
  rules:
  - apiGroups:
    - scale.storage.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - storagescales
  sideEffects: None
