# permissions for end users to edit fusionaccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openshift-fusion-access-operator
    app.kubernetes.io/managed-by: kustomize
  name: fusionaccess-editor-role
rules:
- apiGroups:
  - fusion.storage.openshift.io
  resources:
  - fusionaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fusion.storage.openshift.io
  resources:
  - fusionaccesses/status
  verbs:
  - get
