# permissions for end users to edit purplestorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: purple-storage-rh-operator
    app.kubernetes.io/managed-by: kustomize
  name: purplestorage-editor-role
rules:
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages/status
  verbs:
  - get
