---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages/finalizers
  verbs:
  - update
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages/status
  verbs:
  - get
  - patch
  - update
