---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - PersistentVolume
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - configmap
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - '*'
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints/restricted
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - '*'
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - '*'
  - update
- apiGroups:
  - ""
  - storage.k8s.io
  resources:
  - configmaps
  - persistentvolumeclaims
  - persistentvolumes
  - storageclasses
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - get
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - dnses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - infrastructures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators/finalizers
  verbs:
  - update
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - machineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - localvolumediscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - localvolumediscoveries/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - localvolumediscoveryresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - localvolumediscoveryresults/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - localvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - localvolumesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages/finalizers
  verbs:
  - update
- apiGroups:
  - purple.purplestorage.com
  resources:
  - purplestorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - '*/finalizers'
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - '*/status'
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - approvalrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - approvalrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - asyncreplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - asyncreplications/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - asyncreplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - callhomes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - callhomes/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - callhomes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - cloudcsidisks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - cloudcsidisks/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - cloudcsidisks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - clusterinterconnects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - compressionjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - compressionjobs/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - compressionjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - consistencygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - consistencygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - daemons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - daemons/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - daemons/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - diskjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - diskjobs/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - diskjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - dnss
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - dnss/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - dnss/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - encryptionconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - encryptionconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - encryptionconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - filesystems
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - filesystems/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - filesystems/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - grafanabridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - grafanabridges/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - grafanabridges/status
  verbs:
  - delete
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - guis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - guis/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - guis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - localdisks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - localdisks/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - localdisks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - pmcollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - pmcollectors/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - pmcollectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - recoverygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - recoverygroups/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - recoverygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrexports
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrexports/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrexports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrs/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - regionaldrs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - remoteclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - remoteclusters/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - remoteclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - restripefsjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - restripefsjobs/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - restripefsjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclusterinitnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclusterinitnodes/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclusterinitnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclusters/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclustertiebreaker
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclustertiebreaker/finalizers
  verbs:
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - stretchclustertiebreaker/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - upgradeapprovals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.spectrum.ibm.com
  resources:
  - upgradeapprovals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - use
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - '*'
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  - services/finalizers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resourceNames:
  - local-storage-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - local.storage.openshift.io
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
