# permissions for end users to view storagescales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openshift-storage-scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: storagescale-viewer-role
rules:
- apiGroups:
  - scale.storage.openshift.io
  resources:
  - storagescales
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scale.storage.openshift.io
  resources:
  - storagescales/status
  verbs:
  - get
