# permissions for end users to edit storagescales.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openshift-storage-scale-operator
    app.kubernetes.io/managed-by: kustomize
  name: storagescale-editor-role
rules:
- apiGroups:
  - scale.storage.openshift.io
  resources:
  - storagescales
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scale.storage.openshift.io
  resources:
  - storagescales/status
  verbs:
  - get
