apiVersion: purple.purplestorage.com/v1alpha1
kind: PurpleStorage
metadata:
  labels:
    app.kubernetes.io/name: purple-storage-rh-operator
    app.kubernetes.io/managed-by: kustomize
  name: purplestorage-sample
spec:
  ibm_cnsa_version: "v5.2.2.0"
  machineconfig:
    labels:
      machineconfiguration.openshift.io/role: "worker"
  pull_secret: ""
  ibm_cnsa_cluster:
    create: true

  # TODO(user): Add fields here
