apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: console-plugin-template
spec:
  backend:
    service:
      basePath: /
      name: openshift-storage-scale-operator-console-plugin
      namespace: openshift-operators
      port: 9443
    type: Service
  displayName: Storage Scale Plugin