apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: openshift-storage-scale-operator-console-plugin
  name: openshift-storage-scale-operator-console-plugin
  namespace: openshift-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: openshift-storage-scale-operator-console-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/component: openshift-storage-scale-operator-console-plugin
    spec:
      containers:
      - image: console-plugin:latest
        name: openshift-storage-scale-operator-console-plugin
        ports:
        - containerPort: 9443
          name: pscp-server
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/serving-cert
          name: storage-scale-plugin-cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: storage-scale-plugin-cert
        secret:
          defaultMode: 420
          secretName: storage-scale-plugin-cert