apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- service.yaml
- deployment.yaml
# not supported by OLM :/ Created in code for now
#- consoleplugin.yaml

# components:
# - ../../patches/affinity
# - ../../patches/common

generatorOptions:
  disableNameSuffixHash: true

images:
- name: console-plugin
  newName: quay.io/hybridcloudpatterns/purple-storage-rh-operator-console
  newTag: v6.6.6
