apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: fusion-access-plugin-cert
  labels:
    app.kubernetes.io/component: fusion-access-operator-console-plugin
  name: fusion-access-operator-console-plugin
  namespace: openshift-operators
spec:
  ports:
  - name: 9443-tcp
    port: 9443
    protocol: TCP
    targetPort: pscp-server
  selector:
    app.kubernetes.io/component: fusion-access-operator-console-plugin
  sessionAffinity: None
  type: ClusterIP
