root: true
env:
  browser: true
  es2020: true
plugins:
  - '@typescript-eslint'
  - react
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended-legacy
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  react:
    version: detect
