root: true
env:
  browser: true
  es2022: true
plugins:
  - "@typescript-eslint"
  - react
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended-legacy
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  ecmaFeatures:
    jsx: true
  sourceType: module
settings:
  react:
    version: detect
rules:
  "no-debugger": error
  "no-console": error
  "@typescript-eslint/no-unused-vars":
    - warn
    - destructuredArrayIgnorePattern": "^_"
      argsIgnorePattern": "^_"
      varsIgnorePattern": "^_"

