name: Build manifests

on:
  push:
    paths-ignore:
      - 'console/**'
  pull_request:
    paths-ignore:
      - 'console/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the manifest
      run: |
        make build
