name: Sanity checks

on:
  push:
    paths-ignore:
      - 'console/**'
  pull_request:
    paths-ignore:
      - 'console/**'
jobs:
  build:
    name: Make build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the manifest
      run: |
        make build

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run unit tests
      run: |
        make test
